<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\Base\BaseCrudController;

class UserCrudController extends BaseCrudController
{
    public function setupCreateOperation()
    {
        parent::setupCreateOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField(['name' => 'password', 'attributes' => ['readonly' => 'readonly']]);
    }
}
